# Generated by Django 6.0.4 on 2026-04-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
